wandb_version: 1

T_0:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.21.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.7.16
    start_time: 1679925442.302562
    t:
      1:
      - 1
      - 9
      - 10
      - 11
      - 35
      - 41
      - 48
      - 49
      - 55
      2:
      - 1
      - 9
      - 10
      - 11
      - 35
      - 41
      - 48
      - 49
      - 55
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.7.16
      5: 0.14.0
      6: 4.21.3
      8:
      - 5
batch_size:
  desc: null
  value: 2
check_val_every_n_epochs:
  desc: null
  value: 30
continue_from_checkpoint:
  desc: null
  value: false
dataset:
  desc: null
  value: spine-generic
enable_progress_bar:
  desc: null
  value: false
feature_size:
  desc: null
  value: 16
hidden_size:
  desc: null
  value: 768
init_filters:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0001
loss_func:
  desc: null
  value: dice
max_epochs:
  desc: null
  value: 1000
mlp_dim:
  desc: null
  value: 2048
model:
  desc: null
  value: unetr
model_name:
  desc: null
  value: unetr
num_gpus:
  desc: null
  value: 1
num_heads:
  desc: null
  value: 12
num_workers:
  desc: null
  value: 4
only_eval:
  desc: null
  value: false
optimizer:
  desc: null
  value: adamw
patience:
  desc: null
  value: 200
precision:
  desc: null
  value: 32
save_path:
  desc: null
  value: /home/GRAMES.POLYMTL.CA/lobouz/contrast_agnostic/models_unetr
seed:
  desc: null
  value: 42
visualize_test_preds:
  desc: null
  value: false
