wandb_version: 1

T_0:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.21.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.16
    start_time: 1681829712.241097
    t:
      1:
      - 1
      - 9
      - 10
      - 11
      - 35
      - 41
      - 48
      - 49
      - 55
      2:
      - 1
      - 9
      - 10
      - 11
      - 35
      - 41
      - 48
      - 49
      - 55
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.8.16
      5: 0.14.0
      6: 4.21.3
      8:
      - 5
args/T_0:
  desc: null
  value: 100
args/batch_size:
  desc: null
  value: 2
args/check_val_every_n_epochs:
  desc: null
  value: 30
args/continue_from_checkpoint:
  desc: null
  value: false
args/dataset:
  desc: null
  value: spine-generic_crop
args/dataset_json_name:
  desc: null
  value: dataset_test
args/enable_progress_bar:
  desc: null
  value: false
args/feature_size:
  desc: null
  value: 16
args/hidden_size:
  desc: null
  value: 768
args/init_filters:
  desc: null
  value: 16
args/learning_rate:
  desc: null
  value: 0.0001
args/loss_func:
  desc: null
  value: dice
args/max_epochs:
  desc: null
  value: 2500
args/mlp_dim:
  desc: null
  value: 3072
args/model:
  desc: null
  value: unetr
args/model_name:
  desc: null
  value: unetr
args/num_gpus:
  desc: null
  value: 1
args/num_heads:
  desc: null
  value: 12
args/num_workers:
  desc: null
  value: 4
args/only_eval:
  desc: null
  value: false
args/optimizer:
  desc: null
  value: adamw
args/out_channel:
  desc: null
  value: 1
args/patience:
  desc: null
  value: 200
args/precision:
  desc: null
  value: 32
args/save_path:
  desc: null
  value: /home/GRAMES.POLYMTL.CA/lobouz/contrast_agnostic/models_unetr
args/seed:
  desc: null
  value: 42
args/visualize_test_preds:
  desc: null
  value: false
batch_size:
  desc: null
  value: 2
check_val_every_n_epochs:
  desc: null
  value: 30
continue_from_checkpoint:
  desc: null
  value: false
data_root:
  desc: null
  value: /home/GRAMES.POLYMTL.CA/lobouz/duke/projects/ivadomed/contrast-agnostic-seg/data_processed_mts_fixed_2023-02-16_CROP/data_processed_clean/
dataset:
  desc: null
  value: spine-generic_crop
dataset_json_name:
  desc: null
  value: dataset_test
enable_progress_bar:
  desc: null
  value: false
feature_size:
  desc: null
  value: 16
hidden_size:
  desc: null
  value: 768
init_filters:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0001
loss_func:
  desc: null
  value: dice
loss_function:
  desc: null
  value: null
max_epochs:
  desc: null
  value: 2500
mlp_dim:
  desc: null
  value: 3072
model:
  desc: null
  value: unetr
model_name:
  desc: null
  value: unetr
net:
  desc: null
  value: null
num_gpus:
  desc: null
  value: 1
num_heads:
  desc: null
  value: 12
num_workers:
  desc: null
  value: 4
only_eval:
  desc: null
  value: false
optimizer:
  desc: null
  value: adamw
optimizer_class:
  desc: null
  value: AdamW
out_channel:
  desc: null
  value: 1
patience:
  desc: null
  value: 200
precision:
  desc: null
  value: 32
save_path:
  desc: null
  value: /home/GRAMES.POLYMTL.CA/lobouz/contrast_agnostic/models_unetr
seed:
  desc: null
  value: 42
visualize_test_preds:
  desc: null
  value: false
